default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  <<: *default
  username: rootuser
  password: ""
  database: pet_hotel_development

test:
  <<: *default
  database: pet_hotel_test

production:
  <<: *default
  database: pet_hotel_prod
  url: <%= ENV['DATABASE_URL'] %>
