default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: rootuser
  password: ""

development:
  <<: *default
  database: pet_hotel_development

test:
  <<: *default
  database: pet_hotel_test

production:
  <<: *default
  database: pet_hotel_prod
  url: <%= ENV.fetch("DATABASE_URL") %>
